# 事前定義された行動シーケンス設定
# Aether-SL専用設定

# ドローン機体情報
drone_specs:
  airframe_name: "Aether_SL"
  type: "Streamlined Quadcopter"
  weight: 0.65  # kg
  max_speed: 23.6  # m/s
  max_altitude: 50.0  # m

action_sequences:
  # 基本動作
  - name: "hover"
    action_type: "hover"
    duration: 15.0  # 15秒間ホバリング
    parameters:
      target_altitude: 4.0  # 機体仕様に合わせて調整
      stability_threshold: 0.1
    next_action: null

  - name: "takeoff"
    action_type: "takeoff"
    duration: 4.0  # 4秒間で離陸
    parameters:
      target_altitude: 4.0  # 機体仕様に合わせて調整
      ascent_rate: 1.0  # 機体性能に合わせて調整
    next_action: "hover"

  - name: "landing"
    action_type: "landing"
    duration: 6.0  # 6秒間で着陸
    parameters:
      descent_rate: 0.6  # 機体性能に合わせて調整
      final_altitude: 0.5
    next_action: null

  # 移動動作
  - name: "waypoint_forward"
    action_type: "waypoint"
    duration: 20.0
    parameters:
      target_x: 10.0
      target_y: 0.0
      target_z: 4.0  # 機体仕様に合わせて調整
      approach_speed: 1.0  # 高速対応
    next_action: "hover"

  - name: "waypoint_backward"
    action_type: "waypoint"
    duration: 20.0
    parameters:
      target_x: -10.0
      target_y: 0.0
      target_z: 4.0  # 機体仕様に合わせて調整
      approach_speed: 1.0  # 高速対応
    next_action: "hover"

  - name: "waypoint_right"
    action_type: "waypoint"
    duration: 18.0
    parameters:
      target_x: 0.0
      target_y: 10.0
      target_z: 4.0  # 機体仕様に合わせて調整
      approach_speed: 1.0  # 高速対応
    next_action: "hover"

  - name: "waypoint_left"
    action_type: "waypoint"
    duration: 18.0
    parameters:
      target_x: 0.0
      target_y: -10.0
      target_z: 4.0  # 機体仕様に合わせて調整
      approach_speed: 1.0  # 高速対応
    next_action: "hover"

  # パターン飛行
  - name: "circle_flight"
    action_type: "circle"
    duration: 25.0  # 25秒間で円形飛行
    parameters:
      radius: 6.0
      altitude: 4.0  # 機体仕様に合わせて調整
      angular_velocity: 2.5  # rad/s（高速対応）
      center_x: 0.0
      center_y: 0.0
    next_action: "hover"

  - name: "square_pattern"
    action_type: "square"
    duration: 45.0  # 45秒間で四角形パターン
    parameters:
      side_length: 6.0
      altitude: 4.0  # 機体仕様に合わせて調整
      corner_radius: 1.0
      approach_speed: 1.0  # 高速対応
    next_action: "hover"

  # 複合シーケンス
  - name: "takeoff_and_hover"
    action_type: "takeoff"
    duration: 4.0
    parameters:
      target_altitude: 4.0  # 機体仕様に合わせて調整
      ascent_rate: 1.0  # 機体性能に合わせて調整
    next_action: "hover"

  - name: "exploration_sequence"
    action_type: "takeoff"
    duration: 4.0
    parameters:
      target_altitude: 4.0  # 機体仕様に合わせて調整
      ascent_rate: 1.0  # 機体性能に合わせて調整
    next_action: "waypoint_forward"

  - name: "return_to_base"
    action_type: "waypoint"
    duration: 20.0
    parameters:
      target_x: 0.0
      target_y: 0.0
      target_z: 4.0  # 機体仕様に合わせて調整
      approach_speed: 1.0  # 高速対応
    next_action: "landing"

# 制御パラメータ（機体仕様に合わせて調整）
control_parameters:
  # PID制御ゲイン（機体の制御パラメータに合わせて調整）
  position_p_gain: 1.0  # 機体仕様: MPC_XY_P
  position_i_gain: 0.1   # 機体仕様: MPC_XY_I
  position_d_gain: 0.05  # 機体仕様: MPC_XY_D
  
  attitude_p_gain: 4.8   # 機体仕様: MC_ROLL_P/MC_PITCH_P
  attitude_i_gain: 0.18  # 機体仕様: MC_ROLL_I/MC_PITCH_I
  attitude_d_gain: 0.09  # 機体仕様: MC_ROLL_D/MC_PITCH_D
  
  # 安全制限（機体仕様に合わせて調整）
  max_velocity: 23.6  # m/s（機体仕様: MPC_XY_VEL_MAX）
  max_acceleration: 12.0  # m/s²（機体仕様: MPC_XY_ACC_MAX）
  max_angular_velocity: 2.5  # rad/s（高速対応）
  
  # 動作閾値
  position_tolerance: 0.5  # m
  attitude_tolerance: 0.1  # rad
  velocity_tolerance: 0.2  # m/s

# 安全設定（機体仕様に合わせて調整）
safety_parameters:
  # 高度制限（機体仕様に合わせて調整）
  min_altitude: 0.5  # m
  max_altitude: 50.0  # m（機体仕様: GF_MAX_VER_DIST）
  
  # 範囲制限（機体仕様に合わせて調整）
  max_distance_from_base: 20000.0  # m（機体仕様: GF_MAX_HOR_DIST）
  
  # 緊急停止条件
  emergency_stop_on_collision: true
  emergency_stop_on_low_battery: true
  battery_threshold: 0.2  # 20%
  
  # 機体専用安全設定
  geofence_enabled: true  # 機体仕様: GF_ENABLE
  failsafe_action: "RTL"  # Return to Launch
  rc_loss_timeout: 0.4    # 秒（機体仕様: COM_RC_LOSS_T） 